language: php
php:
  - "5.6"
  - "nightly"
  - "hhvm"
sudo: false
before_script:
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  - cat ~/.composer/config.json
  - printf '{"config":{"github-oauth":{"github.com":"%s"}}}' "$COMPOSER_GITHUB_API"
  - printf '{"config":{"github-oauth":{"github.com":"%s"}}}' "$COMPOSER_GITHUB_API" >  ~/.composer/config.json
  - cat ~/.composer/config.json
  - composer install --no-interaction
  - cp config/app_travis.php config/app.php
  - cp config/oauth_example.php config/oauth.php
  - mysql -e 'create database pmaerr;'
  - wget https://scrutinizer-ci.com/ocular.phar
script:
  - bin/cake migrations migrate
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml.dist
after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
matrix:
  allow_failures:
    - php: "hhvm"
    - php: "nightly"
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
