language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "hhvm"
before_script:
  - composer install --dev --no-interaction
  - mkdir tmp;
  - mkdir logs;
  -	HTTPDUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\ -f1`
  - setfacl -R -m u:${HTTPDUSER}:rwx tmp
  - setfacl -R -d -m u:${HTTPDUSER}:rwx tmp
  - setfacl -R -m u:${HTTPDUSER}:rwx logs
  - setfacl -R -d -m u:${HTTPDUSER}:rwx logs
  - cp config/app_example.php config/app.php
  - cp config/oauth_example.php config/oauth.php
  - mysql -e 'create database pmaerr;'
  - wget https://scrutinizer-ci.com/ocular.phar
script:
  - bin/cake migrations migrate
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml.dist
after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
